// swift-tools-version: 6.1
import PackageDescription

let package = Package(
    name: "BBIconPackage",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "BBIconCore", targets: ["BBIconCore"]),
        .executable(name: "BBIcon", targets: ["BBIcon"]),
    ],
    dependencies: [
        // TestClock, so timers (debounce, reconnect backoff) are tested
        // deterministically instead of with real sleeps. Tests only.
        .package(url: "https://github.com/pointfreeco/swift-clocks", from: "1.0.4"),
    ],
    targets: [
        .target(name: "BBIconCore"),
        .executableTarget(
            name: "BBIcon",
            dependencies: ["BBIconCore"],
            // Generated by `npm run icons`, not committed. The directory's
            // .gitkeep is load-bearing: SwiftPM refuses to build a target whose
            // declared resource path does not exist.
            resources: [.copy("Resources/TrayIcons")]
        ),
        .testTarget(
            name: "BBIconCoreTests",
            dependencies: [
                "BBIconCore",
                .product(name: "Clocks", package: "swift-clocks"),
            ],
            resources: [.copy("Fixtures")]
        ),
    ]
)
